#ifndef COMPONENTS_GLOBAL_H
#define COMPONENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPONENTS_LIBRARY)
#  define COMPONENTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPONENTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPONENTS_GLOBAL_H
